export const clientSettingsInitialState = {
  id: "",
  firstName: "",
  lastName: "",
  fullName: "",
  email: "",
  phone: "",
  avatarUrl: "",
  avatarThumbnailUrl: "",
  avatarUpdatedAt: "",
  profileCompletionPercent: 0,
  emailEnabled: true,
  smsEnabled: true,
  pushEnabled: true,
};
