export const vendorSettingsInitialState = {
  firstName: "",
  lastName: "",
  fullName: "",
  primaryEmail: "",
  secondaryEmail: "",
  mobilePhone: "",
  workPhone: "",
  postCode: "",
  company: "",
  jobTitle: "",
  industry: "",
  avatarUrl: "",
  avatarThumbnailUrl: "",
  avatarUpdatedAt: "",
  profileCompletionPercent: 0,
  textNotifications: false,
  emailNotifications: false,
  pushNotifications: false,
  orderConfirmationPush: false,
};
