export const vendorSettingsInitialState = {
  firstName: "",
  lastName: "",
  primaryEmail: "",
  secondaryEmail: "",
  mobilePhone: "",
  workPhone: "",
  postCode: "",
  company: "",
  jobTitle: "",
  industry: "",
  textNotifications: false,
  emailNotifications: false,
  pushNotifications: false,
  orderConfirmationPush: false,
};
