export const selectHomeState = (state) => state.home;
export const selectAllVendors = (state) => state.home.allVendors;
export const selectSearchedVendors = (state) => state.home.searchedVendors;
export const selectFeaturedVendors = (state) => state.home.featuredVendors;
export const selectPopularVendors = (state) => state.home.popularVendors;
export const selectPopularProducts = (state) => state.home.popularProducts;
export const selectHomeStatus = (state) => state.home.status;
export const selectHomeError = (state) => state.home.error;
export const selectHomeHasLoadedOnce = (state) => state.home.hasLoadedOnce;
